[package]
name = "linfa-lars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = { version = "0.15", features = ["blas", "approx"]}
ndarray-linalg = "0.14"

num-traits = "0.2"
approx = "0.4"
